services:
  express-app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always  
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"